vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /photos
            upload_destination: '%kernel.project_dir%/public/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
